Linux-only check

diff --git a/measurements/experiments/run_network_experimement b/measurements/experiments/run_network_experimement
--- a/measurements/experiments/run_network_experimement
+++ b/measurements/experiments/run_network_experimement
@@ -1,6 +1,12 @@
 #!/bin/bash
 # Run a Network experiment
 
+if ! uname -a | grep -q Linux; 
+then
+    echo "Error: This script should only be run on Linux"
+    exit 1
+fi
+
 ROOT_DIR="/home/nudzhang/Documents/pitometer/measurements/experiments/data/network"
 GIT_BRANCH="measurements"
 NODES_IDS=("1" "2" "3" "4" "5" "6")
